# This workflow runs the kotlin unit tests in sudoqmodel

name: Model Junit Tests for Kotlin

on:
  push:
    branches: [ master, development, feature/* ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: |
          echo "$(pwd)"
          cd sudoq-app
          chmod +x gradlew
    - name: junit tests in model with Gradle
      run: |
          echo "$(pwd)"
          cd sudoq-app
          ./gradlew sudoqmodel:kotlinTests
